version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordpassword123
      POSTGRES_DB: pb138-team-project
    networks:
      - pb138-team-project

networks:
  pb138-team-project:

